name: Docker Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Push to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kizziama/ubuntu
        username: ${{ secrets.DUSER }}
        password: ${{ secrets.DPASS }}
